[package]
name = "advent-of-code-2021"
version = "0.1.0"
authors = ["haraldmaida"]
license = "MIT"
edition = "2021"

description = """Solving Advent of Code Puzzles for 2021"""

repository = "https://github.com/haraldmaida/advent-of-code-2021"
keywords = ["advent", "puzzle"]

[lib]
bench = false

[dependencies]
aoc-runner = "0.3"
aoc-runner-derive = "0.3"
hashbrown = "0.11"

[dev-dependencies]
proptest = "1"
